version: '3'

networks:
    webapi-prod:
        driver: bridge

services:
    webapi:
        image: webapiimage:latest
        depends_on:
            - "db"
        env_file:
            - database.env
        ports:
            - "3000:3000"
        networks:
            - webapi-prod
    
    db:
        image: postgres:9.4
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            - POSTGRESS_PASSWORD=admin
            - POSTGRES_USER=postgres
            - POSTGRES_DB=apidb
        networks:
            - webapi-prod

    react:
        image: reactimage:latest
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment:
            - REACT_APP_API_URI=http://localhost:8000
            - REACT_APP_SERVER_RESOURCE_URI=http://localhost:8000/
        ports:
            - "1337:80"
volumes:
    db_volume:
        