version: '3'

networks:
    webapi-prod:
        driver: bridge

services:
    webapi:
        image: kkacpee/inzpolsl:latest
        depends_on:
            - "db"
        ports:
            - "3030:80"
        networks:
            - webapi-prod
    
    db:
        image: postgres:latest
        ports:
            - "5432"
        restart: always
        command: postgres -c listen_addresses='*'
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=postgres
            - POSTGRES_DB=apidb
        networks:
            - webapi-prod

    react:
        image: kkacpee/inzpolslfront:latest
        volumes:
            - '.:/app'
            - '/app/node_modules'
        environment:
            - REACT_APP_API_URI=http://localhost:3030
            - REACT_APP_SERVER_RESOURCE_URI=http://localhost:3030/
            - NODE_ENV=production
        ports:
            - "1337:80"

        