version: '3'

networks:
    webapi-prod:
        driver: bridge

services:
    webapi:
        image: webapiimage:latest
        depends_on:
            - "db"
        env_file:
            - database.env
        ports:
            - "8000:80"
        networks:
            - webapi-prod
    
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            - POSTGRESS_PASSWORD=admin
            - POSTGRES_USER=postgres
            - POSTGRES_DB=apidb
        networks:
            - webapi-prod
volumes:
    db_volume:
        