FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_ENVIRONMENT="Production"
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "WebApi.dll"]