version: '3.4'

services:
    webapi:
        image: webapiimage:latest
        depends_on:
            - "db"
        ports:
            - "8080:80"
    
    db:
        image: postgres:9.4
        ports:
            - "5050:5432"
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=apidb
volumes:
    db_volume:
        